package intent

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	rt "tachyon/internal/intent/runtime"
)

const generatedDir = "internal/intent/generated/current"

func Generate(bundle Bundle, dir string) error {
	ir, err := Check(bundle)
	if err != nil {
		return err
	}
	if dir == "" {
		dir = generatedDir
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	files := map[string][]byte{}
	reg, err := format.Source([]byte(generateRegistry(ir)))
	if err != nil {
		return fmt.Errorf("format registry: %w", err)
	}
	files["registry_gen.go"] = reg
	testSrc, err := format.Source([]byte(generateRegistryTest(ir)))
	if err != nil {
		return fmt.Errorf("format registry test: %w", err)
	}
	files["registry_gen_test.go"] = testSrc
	benchSrc, err := format.Source([]byte(generateRegistryBench(ir)))
	if err != nil {
		return fmt.Errorf("format registry bench: %w", err)
	}
	files["registry_gen_bench_test.go"] = benchSrc
	for name, src := range files {
		if err := os.WriteFile(filepath.Join(dir, name), src, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func generateRegistry(bundle IRBundle) string {
	var b bytes.Buffer
	b.WriteString("// Code generated by tachyon intent build. DO NOT EDIT.\n\n")
	b.WriteString("package current\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"tachyon/internal/intent/runtime\"\n")
	b.WriteString("\t\"tachyon/internal/router\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var Registry = runtime.Registry{\n")
	b.WriteString(fmt.Sprintf("\tVersion: %q,\n", bundle.Version))
	b.WriteString("\tPolicies: map[string]runtime.PolicyMeta{\n")
	for _, p := range bundle.Policies {
		b.WriteString(fmt.Sprintf("\t\t%q: {\n", p.Name))
		b.WriteString(fmt.Sprintf("\t\t\tName: %q,\n", p.Name))
		b.WriteString(fmt.Sprintf("\t\t\tPriority: %d,\n", p.Priority))
		if len(p.Match) > 0 {
			b.WriteString("\t\t\tMatch: []runtime.MatchCondition{\n")
			for _, cond := range p.Match {
				b.WriteString("\t\t\t\t{")
				b.WriteString(fmt.Sprintf("Field: runtime.MatchField(%q), ", string(cond.Field)))
				if cond.Name != "" {
					b.WriteString(fmt.Sprintf("Name: %q, ", cond.Name))
				}
				b.WriteString(fmt.Sprintf("Value: %q", cond.Value))
				b.WriteString("},\n")
			}
			b.WriteString("\t\t\t},\n")
		}
		if len(p.Request) > 0 {
			b.WriteString("\t\t\tRequest: []runtime.Action{\n")
			for _, act := range p.Request {
				b.WriteString(formatActionLiteral(act))
			}
			b.WriteString("\t\t\t},\n")
		}
		if len(p.Response) > 0 {
			b.WriteString("\t\t\tResponse: []runtime.Action{\n")
			for _, act := range p.Response {
				b.WriteString(formatActionLiteral(act))
			}
			b.WriteString("\t\t\t},\n")
		}
		if len(p.Error) > 0 {
			b.WriteString("\t\t\tError: []runtime.Action{\n")
			for _, act := range p.Error {
				b.WriteString(formatActionLiteral(act))
			}
			b.WriteString("\t\t\t},\n")
		}
		b.WriteString("\t\t\tPrimitives: []string{")
		for i, primitive := range p.Primitives {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", primitive))
		}
		b.WriteString("},\n")
		if p.RequiresClassC {
			b.WriteString("\t\t\tRequiresClassC: true,\n")
		}
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t},\n")
	b.WriteString("}\n\n")
	b.WriteString("func BuildRoutePrograms(routes []router.Rule) (runtime.RoutePrograms, error) {\n")
	b.WriteString("\treturn runtime.BindRoutes(routes, Registry)\n")
	b.WriteString("}\n")
	return b.String()
}

func formatActionLiteral(act rt.Action) string {
	return fmt.Sprintf("\t\t\t\t{Kind: runtime.ActionKind(%q), Str1: %q, Str2: %q, Int1: %d, Int2: %d},\n",
		string(act.Kind), act.Str1, act.Str2, act.Int1, act.Int2)
}

func generateRegistryTest(bundle IRBundle) string {
	var b bytes.Buffer
	b.WriteString("package current\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"testing\"\n\n")
	b.WriteString("\t\"tachyon/internal/intent/runtime\"\n")
	b.WriteString("\t\"tachyon/internal/router\"\n")
	b.WriteString(")\n\n")
	b.WriteString("func generatedRouteSet(t *testing.T, name string) runtime.RoutePolicySet {\n")
	b.WriteString("\tt.Helper()\n")
	b.WriteString("\trp, err := BuildRoutePrograms([]router.Rule{{RouteID: 1, Upstream: \"origin\", Intents: []string{name}}})\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tt.Fatalf(\"build route programs: %v\", err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn rp.ByRouteID[1]\n")
	b.WriteString("}\n\n")
	b.WriteString("func generatedHeaderValue(muts runtime.HeaderMutations, name string) (string, bool) {\n")
	b.WriteString("\treturn muts.Find(name)\n")
	b.WriteString("}\n\n")
	b.WriteString("func generatedStatefulPolicy(name string) bool {\n")
	var statefulNames []string
	for _, p := range bundle.Policies {
		if policyNeedsState(p) {
			statefulNames = append(statefulNames, p.Name)
		}
	}
	if len(statefulNames) == 0 {
		b.WriteString("\treturn false\n")
	} else {
		b.WriteString("\tswitch name {\n")
		b.WriteString("\tcase ")
		for i, name := range statefulNames {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", name))
		}
		b.WriteString(":\n")
		b.WriteString("\t\treturn true\n")
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("func TestRegistryVersion(t *testing.T) {\n")
	b.WriteString("\tif Registry.Version == \"\" {\n")
	b.WriteString("\t\tt.Fatal(\"registry version must be set\")\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")
	b.WriteString("func TestRegistryPolicyNames(t *testing.T) {\n")
	b.WriteString(fmt.Sprintf("\tif got := len(Registry.Policies); got != %d {\n", len(bundle.Policies)))
	b.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"registry policy count: got %%d want %d\", got)\n", len(bundle.Policies)))
	b.WriteString("\t}\n")
	for _, p := range bundle.Policies {
		b.WriteString(fmt.Sprintf("\tif _, ok := Registry.Policies[%q]; !ok {\n", p.Name))
		b.WriteString(fmt.Sprintf("\t\tt.Fatalf(\"missing policy %s\")\n", p.Name))
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	hasCases := false
	for _, p := range bundle.Policies {
		if len(p.Cases) > 0 {
			hasCases = true
			break
		}
	}
	b.WriteString("\nfunc TestGeneratedCases(t *testing.T) {\n")
	if !hasCases {
		b.WriteString("\tt.Skip(\"no generated cases in bundle\")\n")
		b.WriteString("}\n")
	} else {
		for _, p := range bundle.Policies {
			for _, c := range p.Cases {
				b.WriteString(fmt.Sprintf("\tt.Run(%q, func(t *testing.T) {\n", p.Name+"/"+c.Name))
				b.WriteString(fmt.Sprintf("\t\tset := generatedRouteSet(t, %q)\n", p.Name))
				b.WriteString(fmt.Sprintf("\t\treq := runtime.StaticRequest{MethodValue: %q, HostValue: %q, PathValue: %q", defaultString(c.Request.Method, "GET"), defaultString(c.Request.Host, "example.com"), defaultString(c.Request.Path, "/")))
				if c.Request.ClientIP != "" {
					b.WriteString(fmt.Sprintf(", ClientIPValue: %q", c.Request.ClientIP))
				}
				if len(c.Request.Headers) > 0 {
					b.WriteString(", HeadersValue: map[string]string{")
					for _, pair := range sortedMapPairs(c.Request.Headers) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				if len(c.Request.Query) > 0 {
					b.WriteString(", QueryValue: map[string]string{")
					for _, pair := range sortedMapPairs(c.Request.Query) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				if len(c.Request.Cookies) > 0 {
					b.WriteString(", CookieValue: map[string]string{")
					for _, pair := range sortedMapPairs(c.Request.Cookies) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				b.WriteString("}\n")
				b.WriteString("\t\tresult := runtime.ExecuteRequest(set, runtime.NewState(), req, \"origin\")\n")
				if c.Expect.Status != nil || c.Expect.Body != nil {
					b.WriteString("\t\tif !result.HasTerminal {\n")
					b.WriteString("\t\t\tt.Fatal(\"expected terminal response\")\n")
					b.WriteString("\t\t}\n")
					if c.Expect.Status != nil {
						b.WriteString(fmt.Sprintf("\t\tif got := result.Terminal.Status; got != %d {\n", *c.Expect.Status))
						b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"terminal status: got %%d want %d\", got)\n", *c.Expect.Status))
						b.WriteString("\t\t}\n")
					}
					if c.Expect.Body != nil {
						b.WriteString(fmt.Sprintf("\t\tif got := result.Terminal.Body; got != %q {\n", *c.Expect.Body))
						b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"terminal body: got %%q want %%q\", got, %q)\n", *c.Expect.Body))
						b.WriteString("\t\t}\n")
					}
				} else {
					b.WriteString("\t\tif result.HasTerminal {\n")
					b.WriteString("\t\t\tt.Fatalf(\"unexpected terminal response: %#v\", result.Terminal)\n")
					b.WriteString("\t\t}\n")
				}
				if c.Expect.Upstream != "" {
					b.WriteString(fmt.Sprintf("\t\tif got := result.UpstreamOverride; got != %q {\n", c.Expect.Upstream))
					b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"upstream override: got %%q want %%q\", got, %q)\n", c.Expect.Upstream))
					b.WriteString("\t\t}\n")
				}
				if c.Expect.Path != "" {
					b.WriteString(fmt.Sprintf("\t\tif got := result.PathOverride; got != %q {\n", c.Expect.Path))
					b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"path override: got %%q want %%q\", got, %q)\n", c.Expect.Path))
					b.WriteString("\t\t}\n")
				}
				for _, pair := range sortedMapPairs(c.Expect.RequestHeaders) {
					b.WriteString(fmt.Sprintf("\t\tif got, ok := generatedHeaderValue(result.HeaderMutations, %q); !ok || got != %q {\n", pair[0], pair[1]))
					b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"request header mutation %s: got %%q present=%%v want %%q\", got, ok, %q)\n", pair[0], pair[1]))
					b.WriteString("\t\t}\n")
				}
				if len(c.Expect.ResponseHeaders) > 0 {
					b.WriteString("\t\tresponse := runtime.ExecuteResponse(set, func(string) string { return \"\" })\n")
					for _, pair := range sortedMapPairs(c.Expect.ResponseHeaders) {
						b.WriteString(fmt.Sprintf("\t\tif got, ok := generatedHeaderValue(response.HeaderMutations, %q); !ok || got != %q {\n", pair[0], pair[1]))
						b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"response header mutation %s: got %%q present=%%v want %%q\", got, ok, %q)\n", pair[0], pair[1]))
						b.WriteString("\t\t}\n")
					}
				}
				b.WriteString("\t})\n")
			}
		}
		b.WriteString("}\n")
	}

	hasBudgets := false
	for _, p := range bundle.Policies {
		if p.Budget.RequestAllocs != nil || p.Budget.ResponseAllocs != nil {
			hasBudgets = true
			break
		}
	}
	b.WriteString("\nfunc TestGeneratedBudgets(t *testing.T) {\n")
	if !hasBudgets {
		b.WriteString("\tt.Skip(\"no generated budgets in bundle\")\n")
		b.WriteString("}\n")
	} else {
		for _, p := range bundle.Policies {
			if p.Budget.RequestAllocs != nil {
				req := budgetRequestForPolicy(p)
				b.WriteString(fmt.Sprintf("\tt.Run(%q, func(t *testing.T) {\n", p.Name+"/request.allocs"))
				b.WriteString(fmt.Sprintf("\t\tset := generatedRouteSet(t, %q)\n", p.Name))
				b.WriteString("\t\tvar state *runtime.State\n")
				b.WriteString(fmt.Sprintf("\t\tif generatedStatefulPolicy(%q) {\n", p.Name))
				b.WriteString("\t\t\tstate = runtime.NewState()\n")
				b.WriteString("\t\t}\n")
				b.WriteString(fmt.Sprintf("\t\treq := runtime.StaticRequest{MethodValue: %q, HostValue: %q, PathValue: %q", defaultString(req.Method, "GET"), defaultString(req.Host, "example.com"), defaultString(req.Path, "/")))
				if req.ClientIP != "" {
					b.WriteString(fmt.Sprintf(", ClientIPValue: %q", req.ClientIP))
				}
				if len(req.Headers) > 0 {
					b.WriteString(", HeadersValue: map[string]string{")
					for _, pair := range sortedMapPairs(req.Headers) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				if len(req.Query) > 0 {
					b.WriteString(", QueryValue: map[string]string{")
					for _, pair := range sortedMapPairs(req.Query) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				if len(req.Cookies) > 0 {
					b.WriteString(", CookieValue: map[string]string{")
					for _, pair := range sortedMapPairs(req.Cookies) {
						b.WriteString(fmt.Sprintf("%q: %q, ", pair[0], pair[1]))
					}
					b.WriteString("}")
				}
				b.WriteString("}\n")
				b.WriteString("\t\tallocs := testing.AllocsPerRun(100, func() {\n")
				b.WriteString("\t\t\t_ = runtime.ExecuteRequest(set, state, req, \"origin\")\n")
				b.WriteString("\t\t})\n")
				b.WriteString(fmt.Sprintf("\t\tif allocs > %.3f {\n", *p.Budget.RequestAllocs))
				b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"request alloc budget exceeded: got %%0.3f want <= %.3f\", allocs)\n", *p.Budget.RequestAllocs))
				b.WriteString("\t\t}\n")
				b.WriteString("\t})\n")
			}
			if p.Budget.ResponseAllocs != nil {
				b.WriteString(fmt.Sprintf("\tt.Run(%q, func(t *testing.T) {\n", p.Name+"/response.allocs"))
				b.WriteString(fmt.Sprintf("\t\tset := generatedRouteSet(t, %q)\n", p.Name))
				b.WriteString("\t\tallocs := testing.AllocsPerRun(100, func() {\n")
				b.WriteString("\t\t\t_ = runtime.ExecuteResponse(set, func(string) string { return \"\" })\n")
				b.WriteString("\t\t})\n")
				b.WriteString(fmt.Sprintf("\t\tif allocs > %.3f {\n", *p.Budget.ResponseAllocs))
				b.WriteString(fmt.Sprintf("\t\t\tt.Fatalf(\"response alloc budget exceeded: got %%0.3f want <= %.3f\", allocs)\n", *p.Budget.ResponseAllocs))
				b.WriteString("\t\t}\n")
				b.WriteString("\t})\n")
			}
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func generateRegistryBench(bundle IRBundle) string {
	allNames := make([]string, 0, len(bundle.Policies))
	for _, p := range bundle.Policies {
		allNames = append(allNames, p.Name)
	}
	sort.Strings(allNames)

	requestHot := firstPolicy(bundle.Policies, func(p IRPolicy) bool {
		return len(p.Request) > 0 && !hasPrimitive(p, string(rt.ActionRateLimitLocal)) && !p.RequiresClassC
	})
	rateLimit := firstPolicy(bundle.Policies, func(p IRPolicy) bool {
		return hasPrimitive(p, string(rt.ActionRateLimitLocal))
	})
	responseHeaders := firstPolicy(bundle.Policies, func(p IRPolicy) bool {
		return len(p.Response) > 0
	})
	externalAuth := firstPolicy(bundle.Policies, func(p IRPolicy) bool {
		return hasPrimitive(p, string(rt.ActionAuthExternal))
	})

	var b bytes.Buffer
	b.WriteString("package current\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"testing\"\n")
	if externalAuth != nil {
		b.WriteString("\t\"io\"\n")
		b.WriteString("\t\"strings\"\n")
	}
	if rateLimit != nil {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	b.WriteString("\t\"tachyon/internal/intent/runtime\"\n")
	b.WriteString("\t\"tachyon/internal/router\"\n")
	b.WriteString(")\n\n")
	b.WriteString("type benchRoundTripper func(*http.Request) (*http.Response, error)\n\n")
	b.WriteString("func (fn benchRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {\n")
	b.WriteString("\treturn fn(req)\n")
	b.WriteString("}\n\n")
	b.WriteString("func benchmarkRouteSet(names ...string) runtime.RoutePolicySet {\n")
	b.WriteString("\trp, err := BuildRoutePrograms([]router.Rule{{RouteID: 1, Upstream: \"origin\", Intents: names}})\n")
	b.WriteString("\tif err != nil {\n")
	b.WriteString("\t\tpanic(err)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn rp.ByRouteID[1]\n")
	b.WriteString("}\n\n")
	b.WriteString("func BenchmarkNoMatch(b *testing.B) {\n")
	b.WriteString("\tb.ReportAllocs()\n")
	b.WriteString(fmt.Sprintf("\tset := benchmarkRouteSet(%s)\n", quotedArgs(allNames)))
	b.WriteString("\tstate := runtime.NewState()\n")
	b.WriteString("\treq := runtime.StaticRequest{MethodValue: http.MethodGet, HostValue: \"bench.invalid\", PathValue: \"/miss\"}\n")
	b.WriteString("\tfor i := 0; i < b.N; i++ {\n")
	b.WriteString("\t\t_ = runtime.ExecuteRequest(set, state, req, \"origin\")\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func BenchmarkRequestHotPath(b *testing.B) {\n")
	b.WriteString("\tb.ReportAllocs()\n")
	if requestHot == nil {
		b.WriteString("\tb.Skip(\"no request-phase non-rate-limit policy in generated bundle\")\n")
		b.WriteString("}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tset := benchmarkRouteSet(%q)\n", requestHot.Name))
		b.WriteString("\tstate := runtime.NewState()\n")
		b.WriteString("\treq := runtime.StaticRequest{MethodValue: http.MethodGet, HostValue: \"example.com\", PathValue: \"/hot\"}\n")
		b.WriteString("\tfor i := 0; i < b.N; i++ {\n")
		b.WriteString("\t\t_ = runtime.ExecuteRequest(set, state, req, \"origin\")\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("func BenchmarkRequestRateLimitHotKey(b *testing.B) {\n")
	b.WriteString("\tb.ReportAllocs()\n")
	if rateLimit == nil {
		b.WriteString("\tb.Skip(\"no local rate limit policy in generated bundle\")\n")
		b.WriteString("}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tset := benchmarkRouteSet(%q)\n", rateLimit.Name))
		b.WriteString("\tstate := runtime.NewState()\n")
		b.WriteString("\treq := runtime.StaticRequest{MethodValue: http.MethodGet, HostValue: \"example.com\", PathValue: \"/limited\", HeadersValue: map[string]string{\"x-api-key\": \"bench-hot-key\"}, ClientIPValue: \"127.0.0.1\"}\n")
		b.WriteString("\tfor i := 0; i < b.N; i++ {\n")
		b.WriteString("\t\tstate.SetNowTime(time.Unix(int64(i), 0).UTC())\n")
		b.WriteString("\t\t_ = runtime.ExecuteRequest(set, state, req, \"origin\")\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("func BenchmarkResponseHeaders(b *testing.B) {\n")
	b.WriteString("\tb.ReportAllocs()\n")
	if responseHeaders == nil {
		b.WriteString("\tb.Skip(\"no response-phase policy in generated bundle\")\n")
		b.WriteString("}\n\n")
	} else {
		b.WriteString(fmt.Sprintf("\tset := benchmarkRouteSet(%q)\n", responseHeaders.Name))
		b.WriteString("\tfor i := 0; i < b.N; i++ {\n")
		b.WriteString("\t\t_ = runtime.ExecuteResponse(set, func(string) string { return \"\" })\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n\n")
	}

	b.WriteString("func BenchmarkExternalAuthFastFail(b *testing.B) {\n")
	b.WriteString("\tb.ReportAllocs()\n")
	if externalAuth == nil {
		b.WriteString("\tb.Skip(\"no external auth policy in generated bundle\")\n")
	} else {
		b.WriteString(fmt.Sprintf("\tset := benchmarkRouteSet(%q)\n", externalAuth.Name))
		b.WriteString("\tstate := runtime.NewState()\n")
		b.WriteString("\tstate.SetHTTPClient(&http.Client{Transport: benchRoundTripper(func(*http.Request) (*http.Response, error) {\n")
		b.WriteString("\t\treturn &http.Response{StatusCode: http.StatusForbidden, Body: io.NopCloser(strings.NewReader(\"deny\")), Header: make(http.Header)}, nil\n")
		b.WriteString("\t})})\n")
		b.WriteString("\treq := runtime.StaticRequest{MethodValue: http.MethodGet, HostValue: \"example.com\", PathValue: \"/auth\"}\n")
		b.WriteString("\tfor i := 0; i < b.N; i++ {\n")
		b.WriteString("\t\t_ = runtime.ExecuteRequest(set, state, req, \"origin\")\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func quotedArgs(values []string) string {
	if len(values) == 0 {
		return ""
	}
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, fmt.Sprintf("%q", v))
	}
	return strings.Join(parts, ", ")
}

func firstPolicy(policies []IRPolicy, fn func(IRPolicy) bool) *IRPolicy {
	for i := range policies {
		if fn(policies[i]) {
			return &policies[i]
		}
	}
	return nil
}

func hasPrimitive(policy IRPolicy, primitive string) bool {
	for _, p := range policy.Primitives {
		if p == primitive {
			return true
		}
	}
	return false
}

func policyNeedsState(policy IRPolicy) bool {
	for _, primitive := range policy.Primitives {
		switch primitive {
		case string(rt.ActionRateLimitLocal), string(rt.ActionAuthExternal), string(rt.ActionCanary):
			return true
		}
	}
	return false
}

func sortedMapPairs(values map[string]string) [][2]string {
	if len(values) == 0 {
		return nil
	}
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make([][2]string, 0, len(keys))
	for _, k := range keys {
		out = append(out, [2]string{k, values[k]})
	}
	return out
}

func defaultString(v, fallback string) string {
	if v == "" {
		return fallback
	}
	return v
}

func budgetRequestForPolicy(policy IRPolicy) CaseRequest {
	if len(policy.Cases) > 0 {
		return policy.Cases[0].Request
	}
	return CaseRequest{
		Method: "GET",
		Host:   "example.com",
		Path:   "/",
	}
}

func Diff(oldBundle, newBundle Bundle) string {
	oldMap := map[string]Policy{}
	for _, p := range oldBundle.Policies {
		oldMap[p.Name] = p
	}
	newMap := map[string]Policy{}
	for _, p := range newBundle.Policies {
		newMap[p.Name] = p
	}
	var lines []string
	for name, p := range newMap {
		oldPolicy, ok := oldMap[name]
		if !ok {
			lines = append(lines, fmt.Sprintf("added policy %s", name))
			continue
		}
		if matchSignature(oldPolicy) != matchSignature(p) {
			lines = append(lines, fmt.Sprintf("changed policy %s match", name))
		}
		if terminalSignature(oldPolicy) != terminalSignature(p) {
			lines = append(lines, fmt.Sprintf("changed policy %s terminal behavior", name))
		}
		if upstreamSignature(oldPolicy) != upstreamSignature(p) {
			lines = append(lines, fmt.Sprintf("changed policy %s upstream override", name))
		}
		if rateLimitSignature(oldPolicy) != rateLimitSignature(p) {
			lines = append(lines, fmt.Sprintf("changed policy %s rate limit", name))
		}
		if oldPolicy.RequiresClassC != p.RequiresClassC {
			lines = append(lines, fmt.Sprintf("changed policy %s compatibility class", name))
		}
		if strings.Join(oldPolicy.Primitives, ",") != strings.Join(p.Primitives, ",") {
			lines = append(lines, fmt.Sprintf("changed policy %s primitives", name))
		}
	}
	for name := range oldMap {
		if _, ok := newMap[name]; !ok {
			lines = append(lines, fmt.Sprintf("removed policy %s", name))
		}
	}
	if len(lines) == 0 {
		return "no semantic changes"
	}
	return strings.Join(lines, "\n")
}

func matchSignature(policy Policy) string {
	var parts []string
	for _, cond := range policy.Match {
		parts = append(parts, fmt.Sprintf("%s|%s|%s", cond.Field, cond.Name, cond.Value))
	}
	return strings.Join(parts, ";")
}

func terminalSignature(policy Policy) string {
	var parts []string
	for _, action := range policy.Request {
		switch action.Kind {
		case rt.ActionRespond, rt.ActionDeny, rt.ActionRedirect:
			parts = append(parts, fmt.Sprintf("%s|%d|%s", action.Kind, action.Int1, action.Str1))
		}
	}
	return strings.Join(parts, ";")
}

func upstreamSignature(policy Policy) string {
	var parts []string
	for _, action := range policy.Request {
		switch action.Kind {
		case rt.ActionRouteTo, rt.ActionCanary:
			parts = append(parts, fmt.Sprintf("%s|%d|%s", action.Kind, action.Int1, action.Str1))
		}
	}
	return strings.Join(parts, ";")
}

func rateLimitSignature(policy Policy) string {
	var parts []string
	for _, action := range policy.Request {
		if action.Kind == rt.ActionRateLimitLocal {
			parts = append(parts, fmt.Sprintf("%s|%s|%d|%d", action.Kind, action.Str1, action.Int1, action.Int2))
		}
	}
	return strings.Join(parts, ";")
}
